defmodule Andrew.Repo.Migrations.AddFieldsToClient do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:clients) do
      add :phone_number, :text
      add :email, :text
    end
  end

  def down do
    alter table(:clients) do
      remove :email
      remove :phone_number
    end
  end
end