defmodule Andrew.Repo.Migrations.CreateClient do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:clients, primary_key: false) do
      add :address, :text, null: false
      add :license_no, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:clients, [:license_no], name: "clients_unique_license_no_index")
  end

  def down do
    drop_if_exists unique_index(:clients, [:license_no], name: "clients_unique_license_no_index")

    drop table(:clients)
  end
end